# -*- coding: utf-8 -*-
"""myinfo.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xdj1fihR8eIpPbybTfZ2P1TvPSZGcome
"""

#CS175
#Lucas Vandenakker
#myinfo

print('Lucas Vandenakker')
print("123 gray st 043345")
print("723-764-9983")

print("Software Engineering")

print("hello world")

print("something")

